Traceback (most recent call last):
  File "/home/yuxinh/anaconda2/envs/pytorch_env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/yuxinh/anaconda2/envs/pytorch_env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yuxinh/dl_seg/IIC/code/scripts/segmentation/analysis/render_mri.py", line 36, in <module>
    epochs = args.epochs
AttributeError: 'Namespace' object has no attribute 'epochs'
imgs_dataloaders passed:
['test']
Loading restarting config from: /home/yuxinh/dl_seg/IIC/out/777/config.pickle
Creating paired dataloader 0 out of 1 time 2019-11-11 23:39:57.992370
Length of paired datasets vector 1
Number of batches per epoch: 594
dataloader sizes: 594 594 594
/home/yuxinh/dl_seg/IIC/out/777 test best_net
doing net_name best_net.pytorch to /home/yuxinh/dl_seg/IIC/out/777/test/best_net
getting model path /home/yuxinh/dl_seg/IIC/out/777/best_net.pytorch 
Traceback (most recent call last):
  File "/home/yuxinh/anaconda2/envs/pytorch_env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/yuxinh/anaconda2/envs/pytorch_env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yuxinh/dl_seg/IIC/code/scripts/segmentation/analysis/render_mri.py", line 90, in <module>
    torch.load(model_path, map_location=lambda storage, loc: storage))
  File "/home/yuxinh/anaconda2/envs/pytorch_env/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: '/home/yuxinh/dl_seg/IIC/out/777/best_net.pytorch'
